// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6oViAxxmJ0xqiB-95wOXgdxsZvOnbd9Q',
    appId: '1:495931294010:web:305771ac1934cc4e9d5003',
    messagingSenderId: '495931294010',
    projectId: 'blog-app-23eb9',
    authDomain: 'blog-app-23eb9.firebaseapp.com',
    storageBucket: 'blog-app-23eb9.firebasestorage.app',
    measurementId: 'G-WK92LQNEX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBel0liiZCybIfPtqhHtOA7GVmnKSeJVxM',
    appId: '1:495931294010:android:7d005df36e88edc09d5003',
    messagingSenderId: '495931294010',
    projectId: 'blog-app-23eb9',
    storageBucket: 'blog-app-23eb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXb8S55DFTvfZyuXNp_Sr7o31Rh41usIM',
    appId: '1:495931294010:ios:80265c8247a2908a9d5003',
    messagingSenderId: '495931294010',
    projectId: 'blog-app-23eb9',
    storageBucket: 'blog-app-23eb9.firebasestorage.app',
    iosBundleId: 'com.example.blogAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXb8S55DFTvfZyuXNp_Sr7o31Rh41usIM',
    appId: '1:495931294010:ios:80265c8247a2908a9d5003',
    messagingSenderId: '495931294010',
    projectId: 'blog-app-23eb9',
    storageBucket: 'blog-app-23eb9.firebasestorage.app',
    iosBundleId: 'com.example.blogAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6oViAxxmJ0xqiB-95wOXgdxsZvOnbd9Q',
    appId: '1:495931294010:web:e076691fb3e707599d5003',
    messagingSenderId: '495931294010',
    projectId: 'blog-app-23eb9',
    authDomain: 'blog-app-23eb9.firebaseapp.com',
    storageBucket: 'blog-app-23eb9.firebasestorage.app',
    measurementId: 'G-M3CRK2PSHP',
  );
}
